#ifndef FIRMIUS_SHARED_ENUMS_HPP
#define FIRMIUS_SHARED_ENUMS_HPP

#include <cstdint>
#include <string>
#include <vector>

/**
 * @brief Core enumeration types and data contracts for the Firmius Engine.
 */
namespace firmius::shared {

/**
 * @brief Represents the role of a message in a conversation turn.
 */
enum class Role : std::uint8_t {
  System,      ///< System instructions and operational protocol.
  User,        ///< Input from the human user or benchmarks.
  Assistant,   ///< Output generated by the LLM agent.
  ToolResult   ///< Output from a tool execution.
};

/**
 * @brief Types of execution environments supported by the engine.
 */
enum class HostType : std::uint8_t {
  Local,       ///< Direct execution on the local machine.
  Docker,      ///< Sandboxed execution inside a Docker container.
  RemoteSSH    ///< Execution on a remote host via SSH.
};

/**
 * @brief Scopes of operation for tool security and permissioning.
 */
enum class ToolScope : std::uint8_t {
  FilesystemRead,  ///< Reading files from the sandbox.
  FilesystemWrite, ///< Modifying files in the sandbox.
  Process,         ///< Executing shell commands or spawning processes.
  Semantic,        ///< Using vector search or semantic utilities.
  Delegation,      ///< Spawning sub-agents.
  Web,             ///< Performing web searches or fetching URLs.
  Git              ///< Performing git operations.
};

/**
 * @brief Current operational status of an agent.
 */
enum class AgentStatus : std::uint8_t {
  Idle,            ///< Waiting for a task.
  Streaming,       ///< Currently generating a response from the provider.
  ExecutingTool,   ///< Waiting for a tool execution to complete.
  AwaitingInput,   ///< Waiting for user feedback.
  Error            ///< Agent encountered a fatal runtime error.
};

/**
 * @brief Metadata for an LLM model.
 */
struct ModelInfo {
  std::string id;                  ///< Unique identifier for the model (e.g., "gpt-4").
  std::string provider;            ///< The provider that hosts the model.
  std::uint32_t contextWindow = 0; ///< Maximum context window size in tokens.
  std::vector<std::string> modalities; ///< Supported modalities (e.g., "text", "image").
  bool supportsReasoning = false;  ///< True if the model supports native reasoning/thinking deltas.
  double pricePer1MInput = 0.0;    ///< Price in USD per 1M input tokens.
  double pricePer1MOutput = 0.0;   ///< Price in USD per 1M output tokens.

  /**
   * @brief Equality operator for ModelInfo.
   */
  bool operator==(const ModelInfo& other) const = default;
};

}

#endif
