#ifndef FIRMIUS_SHARED_ENUMS_HPP
#define FIRMIUS_SHARED_ENUMS_HPP

#include <cstdint>
#include <map>
#include <string>
#include <vector>

/**
 * @brief Core enumeration types and data contracts for the Firmius Engine.
 */
namespace firmius::shared {

/**
 * @brief Represents the role of a message in a conversation turn.
 */
enum class Role : std::uint8_t {
  System,     ///< System instructions and operational protocol.
  User,       ///< Input from the human user or benchmarks.
  Assistant,  ///< Output generated by the LLM agent.
  ToolResult, ///< Output from a tool execution.
  Error       ///< Structured error information to be displayed directly.
};

/**
 * @brief Visibility level for runtime messages in transcripts.
 */
enum class MessageVisibility : std::uint8_t {
  Visible,  ///< Standard user-facing transcript message.
  Internal, ///< Runtime/internal hint hidden by default in the UI.
};

/**
 * @brief Types of execution environments supported by the engine.
 */
enum class HostType : std::uint8_t {
  Local,    ///< Direct execution on the local machine.
  Docker,   ///< Sandboxed execution inside a Docker container.
  RemoteSSH ///< Execution on a remote host via SSH.
};

struct HostCreationOptions {
  HostType type = HostType::Local;
  std::string containerName = "";
  bool connectToExisting = false;
  bool deleteOnExit = true;
  std::vector<std::string> volumeMounts;  // List of volume mounts in format "host_path:container_path"

  bool operator==(const HostCreationOptions &other) const = default;
};

/**
 * @brief Scopes of operation for tool security and permissioning.
 */
enum class ToolScope : std::uint8_t {
  FilesystemRead,  ///< Reading files from the sandbox.
  FilesystemWrite, ///< Modifying files in the sandbox.
  Process,         ///< Executing shell commands or spawning processes.
  Semantic,        ///< Advanced code analysis or semantic search.
  Delegation,      ///< Spawning sub-agents.
  Web,             ///< Performing web searches or fetching URLs.
  Git,             ///< Git repository operations.
  PlanRead,        ///< Reading persisted plan state.
  PlanWrite,       ///< Creating or mutating persisted plan state.
  ChunkRead,       ///< Reading persisted work chunk state.
  ChunkWrite,      ///< Creating or mutating work chunk state.
  ChunkAssign,     ///< Assigning chunk ownership or execution.
  ChunkReview,     ///< Reviewing or deciding chunk implementation attempts.
};

/**
 * @brief Thread-level permission handling mode.
 */
enum class ThreadPermissionMode : std::uint8_t {
  Request,     ///< Ask before permissioned actions.
  AlwaysAllow, ///< Allow permissioned actions without prompting.
  DenyAll      ///< Deny all permissioned actions.
};

/**
 * @brief Types of permission escalation requests.
 */
enum class PermissionRequestType : std::uint8_t {
  Command,
  Edit
};

/**
 * @brief User response to a permission escalation request.
 */
enum class PermissionResponse : std::uint8_t {
  AllowOnce,
  AllowAlways,
  Deny
};

/**
 * @brief Current operational status of an agent.
 */
enum class AgentStatus : std::uint8_t {
  Idle,            ///< Waiting for a task.
  Streaming,       ///< Currently generating a response from the provider.
  ExecutingTool,   ///< Waiting for a tool execution to complete.
  AwaitingInput,   ///< Waiting for user feedback.
  Compacting,      ///< Summarizing history to free up context window.
  ProviderWaiting, ///< Waiting for initial response from LLM provider.
  Error,           ///< Agent encountered a fatal runtime error.
  Cancelled        ///< Agent was interrupted/aborted by user or engine.
};

/**
 * @brief Lifecycle status for a persisted plan.
 */
enum class PlanStatus : std::uint8_t {
  Draft,
  Active,
  Paused,
  Done,
  Abandoned
};

/**
 * @brief Lifecycle status for a work chunk embedded in a plan.
 */
enum class WorkChunkStatus : std::uint8_t {
  Ready,
  InProgress,
  Implemented,
  Verifying,
  Done,
  Blocked,
  Failed,
  Cancelled
};

/**
 * @brief Execution status for a per-agent todo item.
 */
enum class TodoStatus : std::uint8_t {
  Pending,
  InProgress,
  Done
};

/**
 * @brief Reason why an LLM generation stopped.
 */
enum class StopReason : std::uint8_t {
  Stop,          ///< Natural completion (model chose to stop).
  ToolUse,       ///< Model wants to call one or more tools.
  MaxTokens,     ///< Output was truncated by the token limit.
  ContentFilter, ///< Response was blocked by a safety filter.
  Error,         ///< Provider or network error during generation.
  Cancelled      ///< Generation was aborted by the user or engine.
};

/**
 * @brief Reason why a process execution finished.
 */
enum class ProcessFinishReason : std::uint8_t {
  Natural,   ///< Process exited on its own.
  Timeout,   ///< Timeout occurred, process still running.
  Terminated ///< Process was killed.
};

/**
 * @brief Represents a specific variant of a model (e.g., effort level, hardware
 * tier).
 */
struct ModelVariant {
  std::string variantName;
  std::string extraMetadataJson; // Additional parameters for the variant

  bool operator==(const ModelVariant &other) const = default;
};

/**
 * @brief Metadata for an LLM model.
 */
struct ModelInfo {
  std::string id;       ///< Unique identifier for the model (e.g., "gpt-4").
  std::string provider; ///< The provider that hosts the model.
  std::uint32_t contextWindow = 0; ///< Maximum context window size in tokens.
  std::uint32_t maxOutputTokens = 0; ///< Maximum output token limit, if known.
  std::vector<std::string>
      modalities; ///< Supported modalities (e.g., "text", "image").
  std::vector<ModelVariant>
      variants; ///< Optional variants (e.g., "low", "medium", "max").
  bool supportsReasoning =
      false; ///< True if the model supports native reasoning/thinking deltas.
  double pricePer1MInput = 0.0;  ///< Price in USD per 1M input tokens.
  double pricePer1MOutput = 0.0; ///< Price in USD per 1M output tokens.
  double pricePer1MCacheRead =
      0.0; ///< Price in USD per 1M cached input tokens read.
  double pricePer1MCacheWrite =
      0.0; ///< Price in USD per 1M cache creation tokens.

  /**
   * @brief Equality operator for ModelInfo.
   */
  bool operator==(const ModelInfo &other) const = default;
};

/**
 * @brief Represents an OAuth account stored by a provider.
 */
struct OAuthAccount {
  std::string identifier;  // User-facing account label, usually an email
  std::string refreshToken;
  std::string accessToken;
  int64_t tokenExpiration = 0;  // Epoch seconds
  int64_t lastQuotaRefresh = 0; // Epoch seconds

  // Working state (not necessarily persisted)
  bool rateLimited = false;
  int64_t backoffUntil = 0; // Epoch seconds

  // Arbitrary dynamic metadata stored for the provider's specific needs (e.g.,
  // projectId, quota tracking)
  std::map<std::string, std::string> metadata;

  std::string getIdentifier() const { return identifier; }
};

/**
 * @brief Represents an API key account with rate limiting state.
 */
struct APIKeyAccount {
  std::string identifier;       // Display name (e.g., "Key #1", "Key #2")
  std::string keyPrefix;        // First 5 chars of the API key for display
  std::string apiKey;           // The actual API key
  bool rateLimited = false;
  int64_t backoffUntil = 0;     // Epoch seconds when backoff expires
  std::map<std::string, std::string> metadata; // Provider-specific metadata

  std::string getIdentifier() const { return identifier; }
  std::string getMaskedDisplay() const { return keyPrefix + "..."; }
};

/**
 * @brief Represents a specific quota bucket (e.g., "gemini-pro").
 */
struct QuotaBucket {
  std::string name;
  float remainingFraction = 0.0f;
  std::string resetTime;
  std::string note;
};

} // namespace firmius::shared

#endif
