/** @jsxImportSource @opentui/react */
import { useState, useEffect, useMemo } from "react";
import { useKeyboard } from "@opentui/react";
import useAppStore from "../../store/appStore";
import { client } from "@firmius/shared/api";
import { HostType as HostTypeEnum } from "@firmius/shared/types";
import type { SSHConfig as SharedSSHConfig } from "@firmius/shared/api";

type Step = "host" | "config";
type HostType = "Local" | "Docker" | "Remote";

interface LocalSSHConfig {
  Host: string;
  HostName?: string;
  User?: string;
}

function toLocalSSHConfig(config: SharedSSHConfig): LocalSSHConfig {
  return {
    Host: config.name,
    HostName: config.host,
    User: config.username,
  };
}

/**
 * ThreadWizard: Simplified modal for creating new threads.
 * Purpose is always "orchestrator" (hardcoded).
 * No objective/description - title auto-generated by LLM.
 */
export function ThreadWizard() {
  const activeModal = useAppStore((state) => state.activeModal);
  const setActiveModal = useAppStore((state) => state.setActiveModal);
  const createThread = useAppStore((state) => state.createThread);

  const [step, setStep] = useState<Step>("host");
  const [host, setHost] = useState<HostType>("Local");
  const [sshConfigs, setSshConfigs] = useState<LocalSSHConfig[]>([]);
  const [sshSearch, setSshSearch] = useState("");
  const [dockerImage, setDockerImage] = useState("firmius-sandbox:latest");
  const [dockerRepo, setDockerRepo] = useState("");
  const [dockerActiveField, setDockerActiveField] = useState<"image" | "repo">("image");
  const [selectedIndex, setSelectedIndex] = useState(0);

  const filteredSSH = useMemo(() => {
    return sshConfigs.filter((c) => 
      c.Host.toLowerCase().includes(sshSearch.toLowerCase())
    );
  }, [sshConfigs, sshSearch]);

  const activeSSH = filteredSSH[selectedIndex];

  useEffect(() => {
    if (activeModal === "wizard") {
      setStep("host");
      setSelectedIndex(0);
      setSshSearch("");
      setDockerImage("firmius-sandbox:latest");
      setDockerRepo("");
      setDockerActiveField("image");
    }
  }, [activeModal]);

  useEffect(() => {
    if (step === "config" && host === "Remote") {
      client.getSSHConfigs().then((configs) => setSshConfigs(configs.map(toLocalSSHConfig))).catch(console.error);
    }
  }, [step, host]);

  const next = () => {
    if (step === "host") setStep("config");
    else if (step === "config") handleCreate();
    setSelectedIndex(0);
  };

  const back = () => {
    if (step === "config") setStep("host");
    else setActiveModal(null);
    setSelectedIndex(0);
  };

  const handleCreate = async () => {
    let hostTypeNum: number;
    let options: Record<string, unknown> = {};
    let rootCwd: string;

    if (host === "Local") {
      hostTypeNum = HostTypeEnum.Local;
      options = { cwd: process.cwd() };
      rootCwd = process.cwd();
    } else if (host === "Docker") {
      hostTypeNum = HostTypeEnum.Docker;
      options = { 
        image: dockerImage, 
        containerName: `firmius-tui-${Date.now()}`,
        ...(dockerRepo.trim() && { repo: dockerRepo.trim() }),
      };
      rootCwd = "/app";
    } else {
      hostTypeNum = HostTypeEnum.RemoteSSH;
      options = { 
        sshHost: activeSSH?.Host,
        ...(activeSSH?.HostName && { hostname: activeSSH.HostName }),
        ...(activeSSH?.User && { username: activeSSH.User })
      };
      rootCwd = "/home/workspace";
    }

    const hostConfig: Record<string, unknown> = { 
      type: hostTypeNum,
      options 
    };

    try {
      await createThread({
        purpose: "orchestrator",
        objective: "",
        hostConfig,
        rootCwd,
        workType: "Goal",
      });
      setActiveModal(null);
    } catch (e) {
      console.error("Wizard failed:", e);
    }
  };

  useKeyboard((key) => {
    if (activeModal !== "wizard") return;

    if (key.name === "escape") {
      setActiveModal(null);
      return;
    }

    if (step === "host") {
      const hosts: HostType[] = ["Local", "Docker", "Remote"];
      if (key.name === "left") setSelectedIndex((i) => (i > 0 ? i - 1 : 2));
      if (key.name === "right") setSelectedIndex((i) => (i < 2 ? i + 1 : 0));
      if (key.name === "enter" || key.name === "return") {
        setHost(hosts[selectedIndex] || "Local");
        next();
      }
    } else if (step === "config") {
      if (host === "Remote") {
        if (key.name === "up") setSelectedIndex((i) => (i > 0 ? i - 1 : filteredSSH.length - 1));
        if (key.name === "down") setSelectedIndex((i) => (i < filteredSSH.length - 1 ? i + 1 : 0));
        if (key.name === "backspace") setSshSearch((s) => s.slice(0, -1));
        else if (key.name.length === 1) setSshSearch((s) => s + (key.shift ? key.name.toUpperCase() : key.name));
        if (key.name === "enter" || key.name === "return") next();
      } else if (host === "Docker") {
        if (key.name === "tab") {
          setDockerActiveField((f) => (f === "image" ? "repo" : "image"));
          return;
        }
        if (dockerActiveField === "image") {
          if (key.name === "backspace") setDockerImage((s) => s.slice(0, -1));
          else if (key.name.length === 1) setDockerImage((s) => s + (key.shift ? key.name.toUpperCase() : key.name));
        } else {
          if (key.name === "backspace") setDockerRepo((s) => s.slice(0, -1));
          else if (key.name.length === 1) setDockerRepo((s) => s + (key.shift ? key.name.toUpperCase() : key.name));
        }
        if (key.name === "enter" || key.name === "return") next();
      } else {
        if (key.name === "enter" || key.name === "return") next();
      }
    }

    if (key.name === "tab") back();
  });

  if (activeModal !== "wizard") return null;

  const modalWidth = 60;
  const modalHeight = 16;

  return (
    <box
      position="absolute"
      top="50%"
      left="50%"
      marginTop={-8}
      marginLeft={-30}
      width={modalWidth}
      height={modalHeight}
      backgroundColor="#0A0A0A"
    >
      <box paddingX={1} paddingY={1} backgroundColor="#1A1A1A" flexDirection="row" justifyContent="space-between">
        <text fg="#00FF00"><b>{"THREAD WIZARD // STEP: " + step.toUpperCase()}</b></text>
        <text fg="#444444">ESC TO EXIT // ENTER TO CONTINUE</text>
      </box>

      <box flexGrow={1} padding={2} flexDirection="column">
        {step === "host" && (
          <box flexDirection="row" justifyContent="center">
            {["Local", "Docker", "Remote"].map((h, i) => (
              <box
                key={h}
                paddingX={2}
                paddingY={1}
                backgroundColor={selectedIndex === i ? "#00FF00" : "#1A1A1A"}
                marginLeft={i > 0 ? 2 : 0}
              >
                <text fg={selectedIndex === i ? "#000000" : "#FFFFFF"}>{h}</text>
              </box>
            ))}
          </box>
        )}

        {step === "config" && host === "Remote" && (
          <box flexDirection="column">
            <box backgroundColor="#111111" paddingX={1} marginBottom={1} flexDirection="row">
              <text fg="#00FF00">{"> " + sshSearch}<span bg="#00FF00" fg="#000000"> </span></text>
            </box>
            <box height={8} flexDirection="column">
              {filteredSSH.slice(0, 5).map((config, i) => (
                <box key={config.Host} backgroundColor={selectedIndex === i ? "#333333" : "transparent"} paddingX={1}>
                  <text fg={selectedIndex === i ? "#00FF00" : "#EEEEEE"}>{config.Host}</text>
                </box>
              ))}
            </box>
            <text fg="#666666" marginTop={1}>Select SSH config to connect</text>
          </box>
        )}

        {step === "config" && host === "Docker" && (
          <box flexDirection="column" justifyContent="center" alignItems="center" flexGrow={1}>
            <text fg="#666666">DOCKER IMAGE</text>
            <box backgroundColor={dockerActiveField === "image" ? "#222222" : "#111111"} padding={1} width="80%" flexDirection="row">
              <text fg="#FFFFFF">{dockerImage}<span bg="#00FF00" fg="#000000"> </span></text>
            </box>
            <text fg="#666666" marginTop={2}>Git Repo (optional)</text>
            <box backgroundColor={dockerActiveField === "repo" ? "#222222" : "#111111"} padding={1} width="80%" flexDirection="row">
              <text fg="#FFFFFF">{dockerRepo || "(none)"}<span bg="#00FF00" fg="#000000"> </span></text>
            </box>
            <text fg="#444444" marginTop={1}>TAB to switch fields // ENTER to continue</text>
          </box>
        )}

        {step === "config" && host === "Local" && (
          <box flexDirection="column" justifyContent="center" alignItems="center" flexGrow={1}>
            <text fg="#00FF00"><b>LOCAL HOST CONFIRMED</b></text>
            <text fg="#666666">CWD: {process.cwd()}</text>
            <text fg="#666666">Press ENTER to create thread</text>
          </box>
        )}
      </box>

      <box paddingX={1} paddingY={0} height={1} backgroundColor="#00FF00" justifyContent="center" alignItems="center">
        <text fg="#000000"><b>TAB BACK // ENTER CONTINUE</b></text>
      </box>
    </box>
  );
}
