#ifndef FIRMIUS_CORE_PROMPTCOMPOSER_HPP
#define FIRMIUS_CORE_PROMPTCOMPOSER_HPP

#include "Context.hpp"
#include "agents/PurposeLoader.hpp"
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace firmius::core::prompts {

using firmius::core::Persona;
using firmius::shared::AgentContext;

/**
 * @brief Inputs threaded through every prompt section.
 *
 * The composer is intentionally side-effect free: every dynamic value the
 * sections need flows through this struct. Adding a new dynamic field (e.g.
 * an active workflow descriptor, a branch lineage) means
 * adding one field here and reading it from the relevant section.
 *
 * Stable fields (persona, base prompt path) live on the composer itself.
 * Dynamic, per-turn fields live here.
 */
struct PromptInputs {
  const Persona *persona = nullptr;
  const AgentContext *context = nullptr;
  std::string toolsBlock;          ///< autogenerated tool catalog (legacy)
  std::optional<std::string> activeModeName;     ///< stub for Day 3 modes
  std::optional<std::string> activeWorkflowName; ///< stub for Day 2 workflows
  std::optional<std::string> branchLineage;      ///< stub for branching system
};

/**
 * @brief A single layer of the system prompt.
 *
 * Each section contributes a string. Empty strings are skipped. The composer
 * joins non-empty results with a stable separator so cache hits stay tight
 * for the stable layers.
 */
class IPromptSection {
public:
  virtual ~IPromptSection() = default;

  /// Stable identifier (used for ordering, debugging, future caching).
  virtual std::string id() const = 0;

  /// Render this section's content. Return empty string to skip.
  virtual std::string render(const PromptInputs &inputs) const = 0;
};

/**
 * @brief Layered prompt composer.
 *
 * Stable sections (Identity, Doctrine, Output Style, Persona Voice) come
 * first in fixed order so that prompt-cache hits remain warm across turns.
 * Dynamic sections (Profile, Environment, Active Context, Mode/Workflow/
 * Branch frames) follow in fixed order so the model learns the layout.
 *
 * Adding a new section is one line: register it with the right priority.
 */
class PromptComposer {
public:
  PromptComposer();

  /// Register a section. Lower priority renders earlier.
  void addSection(int priority, std::shared_ptr<IPromptSection> section);

  /// Compose the final system prompt by rendering every section in order.
  std::string compose(const PromptInputs &inputs) const;

  /// Build the default Firmius composer with all builtin sections wired up.
  static PromptComposer buildDefault();

private:
  struct Entry {
    int priority;
    std::shared_ptr<IPromptSection> section;
  };
  std::vector<Entry> entries_;
};

// ─── Builtin sections ───────────────────────────────────────────────────────
//
// Each builtin section is a small concrete class. Day 1 ships with all of
// them; the Mode/Workflow/Branch sections are stubs that render empty
// until their owning subsystems publish state via PromptInputs.

/// Renders prompts/base.md verbatim with placeholder substitution.
class HouseDoctrineSection : public IPromptSection {
public:
  std::string id() const override { return "house_doctrine"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// Output discipline: markdown, citations, tone rules, anti-patterns.
class OutputStyleSection : public IPromptSection {
public:
  std::string id() const override { return "output_style"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// Persona body (the migrated identityPrompt).
class PersonaVoiceSection : public IPromptSection {
public:
  std::string id() const override { return "persona_voice"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// Stub for Cairn-derived per-user/per-project facts (Day 3 fills it).
class ProfileSection : public IPromptSection {
public:
  std::string id() const override { return "profile"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// Refreshed-per-turn block: cwd, host, branch, recent edits, model context.
class EnvironmentSection : public IPromptSection {
public:
  std::string id() const override { return "environment"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// Hinting overlay (per-model behaviour patches). Preserved from legacy compose.
class HintingOverlaySection : public IPromptSection {
public:
  std::string id() const override { return "hinting_overlay"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// Active context (current op, recent files, decisions). Stub for now —
/// we render minimal info from AgentState until the memory pipeline lands.
class ActiveContextSection : public IPromptSection {
public:
  std::string id() const override { return "active_context"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// MODE OVERLAY — injects mode-specific procedural instructions.
/// Day-1 stub: resolves prompts/modes/<name>.md when a mode is active.
class ModeOverlaySection : public IPromptSection {
public:
  std::string id() const override { return "mode_overlay"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// MODE FRAME — current mode + transitions available + how to switch.
class ModeFrameSection : public IPromptSection {
public:
  std::string id() const override { return "mode_frame"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// WORKFLOW FRAME — active workflow name, step, return contract. Stub.
class WorkflowFrameSection : public IPromptSection {
public:
  std::string id() const override { return "workflow_frame"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// BRANCH FRAME — parent agent, task, return contract for delegated agents.
class BranchFrameSection : public IPromptSection {
public:
  std::string id() const override { return "branch_frame"; }
  std::string render(const PromptInputs &inputs) const override;
};

/// Lists registered persona names for delegation hints. Preserved.
class RegisteredPurposesSection : public IPromptSection {
public:
  std::string id() const override { return "registered_purposes"; }
  std::string render(const PromptInputs &inputs) const override;
};

} // namespace firmius::core::prompts

#endif
