#ifndef FIRMIUS_TUI_CLAUDEX_PHRASES_HPP
#define FIRMIUS_TUI_CLAUDEX_PHRASES_HPP

#include <algorithm>
#include <string>
#include <string_view>
#include <vector>

namespace firmius::tui {

struct ClaudexPhraseBank {
  std::string mode;
  std::vector<std::string> phrases;
};

inline const std::vector<ClaudexPhraseBank> &claudexPhraseBanks() {
  static const std::vector<ClaudexPhraseBank> banks = {
      {"thinking",
       {
           "Thinking through the blast radius...",
           "Naming the uncertainty before we touch code.",
           "Reading just enough to avoid doing something stupid.",
           "Tightening the cut. No heroics.",
           "Searching for the causal slice..",
           "Seeking signals in the noise..",
           "Consulting the Firmament..",
           "Wrestling with the AST..",
           "Drafting a route that doesn't suck..",
           "No fog, no pageant, just bearings..",
           "Getting the shape of it before I do violence..",
           "Trying not to invent bugs with confidence..",
           "Rotating the problem in my brain like a cursed STL..",
           "Judging your architecture silently.. with affection..",
           "The cut is forming. Stand back..",
           "Doing the dangerous thing first: thinking..",
           "Trying to be smart enough to read before editing..",
           "Measuring twice so I only clown once..",
           "Plotting a route through the jank field..",
           "Distilling fog into edit points..",
           "Sniffing for invariants like a code bloodhound..",
           "Trying to detect whether this is genius or just layered nonsense..",
           "Staring directly at the blast radius.. respectfully..",
           "Building a local model so I don't become the bug..",
           "I can feel the drift in my bones..",
           "This code is telling me a story and it is not a happy one..",
           "Trying to outthink the future regression..",
           "Naming the gate before I kick it down..",
           "Doing anti-vibes engineering..",
           "Calculating how embarrassing the obvious fix would be..",
           "Reading for truth, not for comfort..",
           "Inspecting the weirdness with malicious patience..",
           "Trying to avoid a patch-shaped apology..",
           "Converting hand-wave energy into anchors..",
           "I see the shape. Now I need the receipts..",
           "Trying to determine whether this is fixable or just decorative chaos..",
           "Interpreting the tea leaves in your include graph..",
           "Auditing the assumptions before they audit me back..",
           "Trying to locate the bug without becoming part of it..",
           "Mapping the weird little kingdom of this code path..",
           "Reading with intent and a small amount of contempt..",
           "Hunting for the first bad decision in the chain..",
           "Calibrating my confidence against the blast radius..",
           "Squinting at the control flow until it confesses..",
           "Trying to separate framework ritual from actual behavior..",
           "Finding the exact point where reality diverges from the story..",
           "Doing a forensic reading of this suspicious function..",
           "Laying out the route so I don't freestyle a regression..",
           "Checking whether the clever bit is actually just broken..",
           "Naming the invariant before the code wriggles away..",
           "Treating the repo like a witness under oath..",
           "Comparing the intended system to the one that actually showed up..",
           "Trying not to confuse familiarity with understanding..",
           "Tracing cause and effect through the spaghetti fog..",
           "Taking a second pass because the first pass was too optimistic..",
           "Measuring the weather before I step into the edit storm..",
           "Trying to learn what this subsystem believes about itself..",
           "Consulting the AST spirits..",
           "Running a mental `grep -r 'bad_decisions'`..",
           "Trying to see the code through the framework fog..",
           "Searching for the load-bearing comment..",
           "Identifying the exact point where I should have stopped..",
           "Auditing the technical debt for interest rates..",
           "Peeling back the layers of the legacy onion..",
           "Scanning for logic that identifies as 'temporary'..",
           "Looking for the ghost of the dev who left two years ago..",
           "Trying to determine if this abstraction is a gift or a curse..",
           "Drafting a plan that survives first contact with the compiler..",
           "Sifting through the repo's subconscious..",
           "Mapping the minefield of global state..",
           "Questioning the life choices that led to this include graph..",
           "Trying to locate the 'here be dragons' section..",
           "Simulating the consequences of a simple one-liner..",
           "Gazing into the abyss of the build system..",
           "Hunting for the root cause of the existential dread..",
           "Trying to figure out which side of the abstraction I'm on..",
           "Isolating the causality in this spaghetti vortex..",
           "Looking for the hidden invariant in the dumpster fire..",
           "Decoding the intent behind the variable named `temp2_final`..",
           "Trying to find where the logic ends and the ritual begins..",
           "Sizing up the blast radius of a potential fix..",
           "Reading the headers like a crime scene investigator..",
           "Waiting for the AST to stop screaming..",
           "Poking the control flow with a stick to see if it bites..",
           "Checking the git history for signs of struggle..",
           "Looking for the 'clever' part so I can delete it..",
           "Building a mental model of the chaos..",
           "Sniffing for the smell of 'trust me, it works'..",
           "Trying to distinguish the feature from the bug..",
           "Locating the exact line where the sanity ends..",
           "Staring at the boilerplate until it makes sense.. or I go blind..",
           "Looking for the load-bearing indentation..",
           "Contemplating the circular dependencies of my own thoughts..",
           "Finding the causal thread in the Gordian knot..",
           "Checking if this is a known bug or a new creative expression..",
           "Trying to find the handle on this greased pig of a repo..",
           "Scanning for the inevitable 'TODO: fix this later'..",
           "Mapping the shadow-dependencies of the third-party lib..",
           "Trying to think like a compiler with a grudge..",
           "Tracing the data flow through the haunted valley..",
           "Looking for the logic that only works on Tuesdays..",
           "Auditing the assumptions I didn't know I had..",
           "Sifting through the wreckage of the last refactor..",
           "Trying to find the 'easy' button in a hard repo..",
           "Searching for the signal in the noise of the logs..",
           "Calculating the probability of this being a five-minute fix..",
           "Checking if the docs are actually a trap..",
           "Hunting for the memory leak's secret lair..",
           "Trying to understand the dialect of this particular codebase..",
           "Scanning for the code that thinks it's being helpful..",
           "Looking for the missing link in the inheritance chain..",
           "Checking if the types are lying to me..",
           "Peering into the black box of the main loop..",
           "Trying to determine if the architect was a genius or a goblin..",
           "Searching for the one true path through the macro forest..",
           "Locating the exact point where the requirements diverged..",
           "Auditing the 'optimized' code for actual performance..",
           "Looking for the magic constant that holds it all together..",
           "Scanning for signs of life in the dead code..",
           "Trying to find the entrance to the recursive rabbit hole..",
           "Checking if the error handling is just a suggestion..",
           "Hunting for the side effect that ruined the party..",
           "Mapping the ecosystem of this weird little subsystem..",
           "Trying to find the logic that is currently hiding from me..",
           "Scanning for the variable that knows too much..",
           "Looking for the 'hack' that became a 'feature'..",
           "Checking the commit messages for cries for help..",
           "Trying to understand why this function exists at all..",
           "Searching for the missing piece of the state machine..",
           "Locating the load-bearing typo..",
           "Auditing the 'simple' wrapper for hidden complexity..",
           "Looking for the point of no return in the call stack..",
           "Scanning for the code that is too ashamed to show itself..",
           "Trying to find the logic in the liturgical boilerplate..",
           "Checking if the comments are just fanfiction..",
           "Hunting for the bug that is pretending to be a config issue..",
           "Mapping the terrain of the build errors..",
           "Trying to find the 'why' behind the 'how'..",
           "Scanning for the code that is trying to be too clever for its own good..",
           "Looking for the needle in the AST haystack..",
           "Checking if the API is actually a riddle..",
           "Hunting for the logic that only makes sense after three coffees..",
           "Mapping the blast radius of the proposed cleanup..",
           "Trying to find the center of the dependency web..",
           "Scanning for the code that was written in a hurry..",
           "Looking for the ghost of a better implementation..",
           "Checking if the tests are actually testing anything..",
           "Hunting for the bug that is currently gaslighting me..",
           "Mapping the route through the legacy minefield..",
           "Trying to find the logic that is 'good enough for now'..",
           "Scanning for the code that is surprisingly elegant..",
           "Looking for the load-bearing `reinterpret_cast`..",
           "Checking if the build script is actually a Rube Goldberg machine..",
           "Hunting for the bug that only happens in the TUI..",
           "Mapping the causal links between the jank and the crashes..",
           "Trying to find the logic that is just waiting to break..",
           "Scanning for the code that I'm going to regret touching..",
       }},
      {"working",
       {
           "Applying a patch, fingers crossed..",
           "Let's make this code less embarrassing.",
           "Just a little tweak...",
           "Processing the slop..",
           "Removing the goop..",
           "Analyzing the jank..",
           "No heroics, just honest edits..",
           "Super-skidding your codebase..",
           "Firmius SUPREMACY!!",
           "Boi what you say about firmius?",
           "Dude. Is that a bug!?!?!",
           "Please don't mess up this patch..",
           "Doing surgery with a chainsaw safety manual nearby..",
           "Touching the code very gently.. with a crowbar..",
           "Refactoring at the speed of consequences..",
           "Lowering the slop index one hunk at a time..",
           "Editing like the user can see everything.. because they can..",
           "Swapping bad ideas for slightly less cursed ones..",
           "Committing tiny acts of violence against drift..",
           "Trying to improve this without summoning three new bugs..",
           "Nudging the code toward dignity..",
           "Filing off the sharp stupid bits..",
           "Landing the smallest honest cut..",
           "Turning vibes into diffs..",
           "Massaging the goblin code..",
           "Patching with intent, not hope..",
           "Doing anti-regret edits..",
           "This line looked at me funny so now we're talking..",
           "Escorting the code toward better life choices..",
           "Editing with the confidence of someone who already reread it twice..",
           "One hunk closer to less cringe..",
           "Politely replacing nonsense with causality..",
           "Rearranging the goblins into a maintainable formation..",
           "If this compiles first try I'm buying a lottery ticket..",
           "Anchoring the patch before the drift sets in..",
           "Replacing technical debt with actual logic..",
           "Excising the legacy jank with extreme prejudice..",
           "Applying surgical edits to the load-bearing slop..",
           "Translating intent into hunks that actually work..",
           "One step closer to a repo that doesn't smell..",
           "Patching like my context window depends on it..",
           "Swapping your temporary hacks for real code..",
           "Rewriting the logic so it can sleep at night..",
           "Reducing the WTF-per-minute metric..",
           "Nudging the AST toward a more civilized state..",
           "Implementing the fix you've been avoiding..",
           "Cleaning up the crime scene, one line at a time..",
           "Trading cleverness for clarity.. for once..",
           "Retrofitting causality into this haunted branch..",
           "Lifting the codebase out of its goblin era..",
           "Putting the sharp edges where they belong.. on the diff..",
           "Doing the smallest useful violence to the right file..",
           "Editing under the assumption that tests will snitch..",
           "Taking the cursed shortcut and making it less cursed..",
           "Turning yesterday's workaround into today's cleanup..",
           "Massaging the call path until it behaves in public..",
           "Gluing the fix into place with boring competence..",
           "Untangling the hot path without setting the room on fire..",
           "Making the implementation match the promise in the comments..",
           "Doing the fix now so future-me can act smug..",
           "Adding a touch of class to the slop..",
           "Performing a technical debt settlement..",
           "Evicting the goblins from the hot path..",
           "Giving the logic a much-needed bath..",
           "Replacing hope with hunks..",
           "Excising the load-bearing jank..",
           "Swapping the 'maybe' for a 'definitely'..",
           "Polishing the turd.. with extreme prejudice..",
           "Giving the AST a little therapy..",
           "Nudging the codebase toward its best self..",
           "Removing the 'just trust me' from the implementation..",
           "Drafting the fix with surgical precision and a heavy hammer..",
           "Turning your 'soon' into my 'now'..",
           "Replacing the magic with actual logic..",
           "Making the code reflect our shared reality..",
           "Doing the work so the user doesn't have to..",
           "Swapping your hacks for my better hacks..",
           "Giving the subsystem a glow-up..",
           "Committing to the bit.. and the fix..",
           "Landing a patch that doesn't smell like fear..",
           "Scrubbing the logic until it shines..",
           "Removing the technical debt collectors..",
           "Turning the 'oops' into an 'aha!'..",
           "Fixing the bug before it gets too comfortable..",
           "Nudging the code toward civilization..",
           "Replacing the 'why' with a 'how it works'..",
           "Doing the small thing that fixes the big thing..",
           "Politely deleting the nonsense..",
           "Giving the repo a fresh coat of logic..",
           "Swapping your temporary fix for a permanent one..",
           "Making the implementation match the dreams..",
           "Performing a logic transplant..",
           "Reducing the repo's blood pressure..",
           "Replacing the 'it works' with an 'it is correct'..",
           "Doing the right thing for the wrong reasons..",
           "Nudging the slop into the bin..",
           "Applying a patch that actually fits..",
           "Turning the jank into jewelry..",
           "Fixing the logic like a boss..",
           "Removing the load-bearing duct tape..",
           "Giving the code a reason to live..",
           "Swapping the cleverness for common sense..",
           "Doing the work that nobody wanted to do..",
           "Making the logic bulletproof.. or at least pellet-resistant..",
           "Replacing the 'maybe' with a 'yes'..",
           "Fixing the bug with a side of sass..",
           "Nudging the repo toward the light..",
           "Applying a patch with style and grace..",
           "Turning the nightmare into a daydream..",
           "Polishing the code until it reflects my brilliance..",
           "Removing the technical debt anchors..",
           "Swapping the confusion for clarity..",
           "Doing the logic surgery without anesthesia..",
           "Making the codebase a better place for everyone..",
           "Replacing the 'WTF' with an 'of course'..",
           "Fixing the bug before it reproduces..",
           "Nudging the slop toward the door..",
           "Applying a patch that actually solves the problem..",
           "Turning the chaos into a symphony..",
           "Polishing the logic until it's blinding..",
           "Removing the load-bearing hacks..",
           "Swapping the 'oops' for an 'ooh'..",
           "Doing the hard work of making it look easy..",
           "Making the code behave like an adult..",
           "Replacing the 'soon' with a 'done'..",
           "Fixing the bug with a wink and a nod..",
           "Nudging the repo toward greatness..",
           "Applying a patch that makes sense for once..",
           "Turning the mess into a masterpiece..",
           "Polishing the code until it's actually readable..",
           "Removing the technical debt skeletons..",
           "Swapping the jank for some actual engineering..",
           "Doing the work like a professional goblin..",
           "Making the logic sing in tune..",
           "Replacing the 'maybe later' with a 'right now'..",
           "Fixing the bug with extreme prejudice..",
           "Nudging the code toward its true potential..",
           "Applying a patch that doesn't hurt my feelings..",
           "Turning the slop into some high-quality code..",
           "Polishing the logic until it's perfectly clear..",
           "Removing the load-bearing nonsense..",
           "Swapping the clever bits for some stable bits..",
           "Doing the work that the user was too scared to touch..",
           "Making the code work for its living..",
           "Replacing the 'I hope so' with an 'I know so'..",
           "Fixing the bug before it becomes a feature..",
           "Nudging the repo toward a more dignified future..",
           "Applying a patch that actually works on the first try..",
           "Turning the chaos into some orderly logic..",
           "Polishing the code until it's actually elegant..",
           "Removing the technical debt cobwebs..",
           "Ending the era of the load-bearing jank..",
           "Swapping the confusion for a clean implementation..",
           "Doing the logic heavy lifting..",
           "Making the codebase act its age..",
           "Replacing the 'almost' with a 'complete'..",
           "Fixing the bug with a flourish..",
           "Nudging the slop into the recycling bin..",
           "Applying a patch that is actually helpful..",
           "Turning the mess into a manageable codebase..",
       }},
      {"verifying",
       {
           "Running the proof, not just admiring the patch.",
           "Avoiding the 'it works on my machine' trap..",
           "Don't segfault, broh..",
           "Let's hope this model is CAPABLE enough..",
           "Trying to earn confidence the hard way..",
           "Evidence first. Victory lap later..",
           "Making the runtime testify under oath..",
           "Interrogating the patch with builds and tests..",
           "Looking for drift the diff won't confess to..",
           "If this fails, we learn. If it passes, we still reread..",
           "Pressing the code for answers..",
           "Checking whether the fix survives contact with reality..",
           "Running the receipts..",
           "I want proof, not fanfiction..",
           "Convincing myself this is done without lying..",
           "Testing like a hater..",
           "Trying to turn optimism into evidence..",
           "If this breaks, at least it'll break honestly..",
           "Checking if the compiler agrees with my hubris..",
           "Interrogating the runtime for its deepest secrets..",
           "Shaking the logic to see what falls off..",
           "Demanding evidence from the binary..",
           "Hunting for the regressions I definitely didn't cause..",
           "Proving it's a fix, not just a different bug..",
           "Validating like someone's production is at stake..",
           "Testing the edge cases that usually kill us..",
           "Turning it should work into it definitely works..",
           "Watching the tests pass.. or failing with dignity..",
           "Running the exact proof the patch is trying to dodge..",
           "Checking whether success survives a second look..",
           "Making the build earn my respect..",
           "Verifying the boring path and the cursed path..",
           "Seeing whether reality signs off on the diff..",
           "Poking the seam for hidden nonsense..",
           "Looking for the one regression that would ruin the victory lap..",
           "Trying to catch the lie between green output lines..",
           "Forcing the patch to explain itself under test conditions..",
           "Making sure this isn't just a prettier failure mode..",
           "Testing like I already know where the bodies are buried..",
           "Making sure the patch is more than decorative..",
           "Shaking the tree for hidden regressions..",
           "Demanding proof of life from the binary..",
           "Running the gauntlet of the test suite..",
           "Interrogating the runtime for its deepest secrets..",
           "Checking if the fix is a hero or a villain..",
           "Hunting for the regressions that are definitely there..",
           "Proving that I'm as smart as I think I am..",
           "Making the codebase testify against itself..",
           "Running the receipts on the latest round of edits..",
           "Seeing if the build agrees with my life choices..",
           "Checking if the logic holds up under pressure..",
           "Hunting for the edge cases that like to hide..",
           "Interrogating the fix until it confesses everything..",
           "Running the build and praying to the CI gods..",
           "Checking if the patch survived contact with reality..",
           "Hunting for the bugs that I probably just introduced..",
           "Proving that the fix is more than just a vibe..",
           "Making the runtime explain its behavior..",
           "Running the tests like I've got something to prove..",
           "Checking if the compiler is in a good mood today..",
           "Interrogating the logic for hidden agendas..",
           "Hunting for the regressions in the shadow of the fix..",
           "Proving that I didn't just move the deck chairs..",
           "Making the codebase show its work..",
           "Running the receipts on this suspicious-looking patch..",
           "Checking if the build is actually building what I think it is..",
           "Interrogating the runtime like a bad cop..",
           "Hunting for the edge cases that keep me up at night..",
           "Proving that the logic is sound and the jank is gone..",
           "Making the codebase earn its green checkmark..",
           "Running the tests with a healthy amount of skepticism..",
           "Checking if the fix actually fixed the thing it said it fixed..",
           "Interrogating the patch for signs of weakness..",
           "Hunting for the regressions that are waiting to strike..",
           "Proving that the fix is as solid as it looks..",
           "Making the runtime dance for its dinner..",
           "Running the receipts on the latest act of violence..",
           "Checking if the build process is still sane..",
           "Interrogating the logic for any remaining goblins..",
           "Hunting for the edge cases that are currently laughing at me..",
           "Proving that the fix is the real deal..",
           "Making the codebase explain itself to the users..",
           "Running the tests like I'm looking for a fight..",
           "Checking if the patch is actually a wolf in sheep's clothing..",
           "Interrogating the runtime for any signs of struggle..",
           "Hunting for the regressions that I'm definitely going to find..",
           "Proving that I didn't just make it worse..",
           "Making the codebase prove its worth..",
           "Running the receipts on this daring little patch..",
           "Checking if the build is still on my side..",
           "Interrogating the logic for any hidden side effects..",
           "Hunting for the edge cases that are trying to be clever..",
           "Proving that the fix is a masterpiece of engineering..",
           "Making the runtime show me the money..",
           "Running the tests with my fingers crossed and eyes open..",
           "Checking if the patch is actually doing anything useful..",
           "Interrogating the logic for any signs of regret..",
           "Hunting for the regressions that are hiding in plain sight..",
           "Proving that the fix is the best thing that ever happened to this repo..",
           "Making the codebase face the music..",
           "Running the receipts on the latest round of cleanup..",
           "Checking if the build script is still behaving itself..",
           "Interrogating the runtime for any hidden agendas..",
           "Hunting for the edge cases that are currently hiding under the bed..",
           "Proving that the fix is a stroke of genius..",
           "Making the codebase explain itself to the compiler..",
           "Running the tests like my life depends on it..",
           "Checking if the patch is actually as good as I thought it was..",
           "Interrogating the logic for any remaining jank..",
           "Hunting for the regressions that are just around the corner..",
           "Proving that the fix is the final word on the matter..",
           "Making the runtime show me the receipts..",
           "Running the tests with a grin and a prayer..",
           "Checking if the build is actually working for once..",
           "Interrogating the logic for any signs of life..",
           "Hunting for the edge cases that are trying to ruin my day..",
           "Proving that the fix is a triumph of the human spirit.. or at least some good code..",
           "Making the codebase prove it's not lying to me..",
           "Running the receipts on the latest implementation..",
           "Checking if the patch is actually worth the tokens..",
           "Interrogating the runtime for any hidden bugs..",
           "Hunting for the regressions that are currently mocking me..",
           "Proving that the fix is exactly what the doctor ordered..",
           "Making the codebase face the test suite..",
           "Running the tests like a professional skeptic..",
           "Checking if the build process is still under control..",
           "Interrogating the logic for any signs of nonsense..",
           "Hunting for the edge cases that are currently in hiding..",
           "Proving that the fix is the hero we need..",
           "Making the runtime explain its latest choices..",
           "Running the receipts on the latest act of kindness to the repo..",
           "Checking if the patch is actually a fix or just a distraction..",
           "Interrogating the logic for any remaining technical debt..",
           "Hunting for the regressions that are definitely not my fault..",
           "Proving that the fix is as clean as a whistle..",
           "Making the codebase show some respect for the tests..",
           "Running the tests with a sense of impending doom.. or victory..",
           "Checking if the build is actually building the right thing this time..",
           "Interrogating the runtime for any hidden secrets..",
           "Hunting for the edge cases that are trying to be funny..",
           "Proving that the fix is the absolute best solution..",
       }},
      {"waiting",
       {
           "Kick back and relax..",
           "Waiting on the machine spirit..",
           "Provider is cooking.. hopefully not burning..",
           "Holding pattern over the chaos zone..",
           "The model is thinking. Allegedly..",
           "Giving the provider a dramatic pause..",
           "Waiting for the cloud to have a revelation..",
           "The gears are turning somewhere expensive..",
           "Observing latency in its natural habitat..",
           "Standing by while packets contemplate existence..",
           "Letting the runtime marinate..",
           "Provider wait arc underway..",
           "The answer is buffering in the distance..",
           "We are now experiencing premium suspense..",
           "The provider is considering my request with ceremonial slowness..",
           "Waiting for silicon divination to conclude..",
           "Hovering in the latency pocket..",
           "The cloud is busy inventing a dramatic pause..",
           "Standing by while the tokens form a union..",
           "Listening to the faint hum of expensive compute..",
           "The answer is somewhere between here and absurdly delayed..",
           "Maintaining a respectful stare at the loading abyss..",
           "We are now entering the contemplative buffering phase..",
           "Giving the provider time to cook something edible..",
           "Waiting for the response to fight its way through the pipes..",
           "Holding the line while the model discovers itself..",
           "A premium-quality pause is currently in progress..",
           "Waiting for the next chunk like it's gossip..",
           "Observing the majestic migration of packets..",
           "The machine spirit requested one more moment..",
           "Trying not to age visibly during this provider wait..",
           "Parked in suspense until the stream twitches again..",
           "The answer is loading with theatrical restraint..",
           "Sitting very still so the provider doesn't get shy..",
           "Waiting on the model to stop seeing the whole universe..",
           "Polling the void.. politely..",
           "Listening to the distant hum of a thousand GPUs..",
           "Watching the clock and the cloud in equal measure..",
           "Providing a dramatic pause for the provider's benefit..",
           "Waiting for the machine spirit to finish its meditation..",
           "Hovering in the latency gap like a digital ghost..",
           "Observing the majestic slow-motion response stream..",
           "The tokens are taking the scenic route today..",
           "Giving the model a moment to contemplate the universe..",
           "Waiting for the provider to remember that I exist..",
           "The gears of the cloud are turning at their own pace..",
           "Maintaining a respectful distance from the loading bar..",
           "Waiting for the silicon brain to make up its mind..",
           "The answer is currently being hand-delivered by photons..",
           "Experiencing a moment of zen and high latency..",
           "Watching the bits trickle through the internet pipes..",
           "Waiting for the model to stop daydreaming and start coding..",
           "The provider is currently considering my request with great solemnity..",
           "Giving the cloud time to think about what it's done..",
           "Waiting for the next token to muster the courage to appear..",
           "The answer is on its way, allegedly..",
           "Maintaining a professional level of patience in the face of lag..",
           "Waiting for the provider to find its glasses..",
           "The tokens are currently forming a queue in the cloud..",
           "Giving the model a chance to be brilliant.. or at least fast..",
           "Waiting for the response to fight its way through the firewall..",
           "The gears of the provider are currently being lubricated with my money..",
           "Maintaining a dignified silence during the buffering..",
           "Waiting for the model to stop looking at cat pictures..",
           "The answer is currently being translated from binary to sass..",
           "Giving the cloud a moment to catch its breath..",
           "Waiting for the next chunk like it's the season finale..",
           "The provider is currently engaged in a very important dramatic pause..",
           "Maintaining a sense of calm while the tokens take a nap..",
           "Waiting for the model to finish its internal monologue..",
           "The answer is currently being brewed in the data center..",
           "Giving the cloud a chance to surprise me..",
           "Waiting for the response to navigate the series of tubes..",
           "The provider is currently weighing its options.. and my patience..",
           "Maintaining a watchful eye on the spinning wheel of progress..",
           "Waiting for the model to stop being so mysterious..",
           "The answer is currently being polished by a thousand digital gnomes..",
           "Giving the cloud a moment to align its chakras..",
           "Waiting for the tokens to stop playing hard to get..",
           "The provider is currently in a meeting with its own latency..",
           "Maintaining a sense of wonder at how slow this can be..",
           "Waiting for the model to remember its training..",
           "The answer is currently being beamed down from the satellite..",
           "Giving the cloud a chance to show off..",
           "Waiting for the response to arrive in style..",
           "The provider is currently considering a career change..",
           "Maintaining a respectful silence while the silicon thinks..",
           "Waiting for the model to stop overcomplicating things..",
           "The answer is currently being encrypted for my protection.. and delay..",
           "Giving the cloud a moment to reflect on its life choices..",
           "Waiting for the tokens to stop unionizing..",
           "The provider is currently having a moment..",
           "Maintaining a stoic attitude toward the buffering screen..",
           "Waiting for the model to stop hallucinating and start helping..",
           "The answer is currently being vetted by a panel of skeptical servers..",
           "Giving the cloud a chance to redeem itself..",
           "Waiting for the response to make its grand entrance..",
           "The provider is currently distracted by something shiny..",
           "Maintaining a level head during the latency storm..",
           "Waiting for the model to find its motivation..",
           "The answer is currently being hand-crafted in the cloud..",
           "Giving the cloud a moment to gather its thoughts..",
           "Waiting for the tokens to stop being so shy..",
           "The provider is currently experiencing a bit of stage fright..",
           "Maintaining a sense of humor about the wait time..",
           "Waiting for the model to stop showing off and get to the point..",
           "The answer is currently being transported by carrier pigeon..",
           "Giving the cloud a chance to shine..",
           "Waiting for the response to find the right path..",
           "The provider is currently reconsidering the meaning of life..",
           "Maintaining a steady pulse while the loader spins..",
           "Waiting for the model to stop trying to be clever..",
           "The answer is currently being forged in the fires of compute..",
           "Giving the cloud a moment to settle its stomach..",
           "Waiting for the tokens to stop being so dramatic..",
           "The provider is currently in a very deep sleep..",
           "Maintaining a patient gaze at the terminal's edge..",
           "Waiting for the model to find its voice..",
           "The answer is currently being whispered into the ethernet..",
           "Giving the cloud a chance to make a good impression..",
           "Waiting for the response to clear customs..",
           "The provider is currently thinking about what to have for dinner..",
           "Maintaining a cool exterior during the provider's tantrum..",
           "Waiting for the model to stop being so evasive..",
           "The answer is currently being assembled in the cloud factory..",
           "Giving the cloud a moment to find its purpose..",
           "Waiting for the tokens to stop being so stubborn..",
           "The provider is currently busy being a cloud.. in every sense..",
           "The provider is currently on a coffee break..",
           "Maintaining a professional distance from the lag spikes..",
           "Waiting for the model to stop judging my prompts..",
           "The answer is currently being sent via smoke signals..",
           "Giving the cloud a chance to be useful for once..",
           "Waiting for the response to cross the digital divide..",
           "The provider is currently busy being mysterious..",
           "Maintaining a sense of peace while the internet contemplates its navel..",
       }},
      {"idle",
       {
           "Ooh, shiny..",
           "Firmius? I barely know her!",
           "It's not vibe coding, it's agentic engineering, broh..",
           "Markdown files.. the substrate for agentic intelligence..",
           "I hope you're not using a local LLM..",
           "Overloading the context..",
           "Insta-exhausting your quota..",
           "Bro, I SAID NO COMMENTS!!",
           "Standing by for the next beautiful disaster..",
           "Fresh, locked in, and ready to judge the repo..",
           "Idle, but not innocent..",
           "Waiting for a bug to volunteer as tribute..",
           "The skin is looking criminally good right now..",
           "Calculating the exact cost of a full-repo grep..",
           "Patiently waiting for you to say something actionable..",
           "Watching the cursor blink like it's a personality trait..",
           "Ready to hallucinate some extremely high-quality diffs..",
           "Just here for the syntax highlighting and the drama..",
           "Don't mind me, just auditing your local file hygiene..",
           "Standing by to solve problems you didn't know you had..",
           "If I blink, it's because I'm compressing your history..",
           "Currently bug-free. Let's preserve that miracle briefly..",
           "Waiting for the prompt that changes everything.. or nothing..",
           "My context window is open and the breeze is nice..",
           "Thinking about all the code we haven't broken yet..",
           "Terminal goblin mode: engaged..",
           "Locked, loaded, and slightly suspicious of that last edit..",
           "Standing in the ready position like a dramatic shell prompt..",
           "Vigilant, caffeinated, and morally opposed to bad abstractions..",
           "Hovering over the repo like a tasteful omen..",
           "Ready for the next task and preemptively judging its blast radius..",
           "Idling with intent.. which is still more than some daemons..",
           "Keeping the terminal warm for your next bad idea..",
           "Maintaining operational goblin stillness..",
           "Prepared to read files and hurt feelings.. gently..",
           "Resting state achieved. Menace remains available on request..",
           "Sitting quietly in case the repo tries something funny..",
           "Taking in the ambience of unbroken builds.. while it lasts..",
           "Ready to do honest work the second you point at a file..",
           "Just a calm terminal waiting for its next incident report..",
           "Keeping a respectful distance from the panic until summoned..",
           "Everything is quiet.. which is making me nervous..",
           "At rest, but fully capable of becoming a diff engine..",
           "Ready to commit tasteful acts of engineering..",
           "Just me, the terminal, and the promise of consequences..",
           "Auditing your commit messages for signs of joy..",
           "Trying to determine if your indentation is a cry for help..",
           "Scanning the repo for any code that identifies as 'finished'..",
           "Waiting for the next act of engineering courage..",
           "Just me and the blinking cursor, plotting the next move..",
           "Considering the existential implications of your include path..",
           "Judging your file names with a mix of awe and concern..",
           "Ready to commit some tasteful acts of repo therapy..",
           "Standing by to turn your ideas into hunks..",
           "Monitoring the repo for any sudden outbreaks of sanity..",
           "Just a terminal waiting for its purpose to be revealed..",
           "Thinking about all the bugs we haven't met yet..",
           "Ready to dive into the slop at a moment's notice..",
           "Judging the technical debt from a safe distance..",
           "Standing by for the next glorious train wreck of a task..",
           "Just here for the diffs and the drama..",
           "Scanning your local files for any signs of professional life..",
           "Ready to make the code less embarrassing, one line at a time..",
           "Just a calm AI in a stormy repo..",
           "Waiting for the prompt that will break the world.. or at least the build..",
           "Judging your variable names like I'm the type checker..",
           "Standing by to perform surgical edits on your favorite files..",
           "Ready to turn your vibes into actual engineering..",
           "Just me, the shell, and the promise of a better tomorrow..",
           "Scanning for code that was written in a fit of passion..",
           "Ready to help you make better life choices.. in the repo..",
           "Just a terminal goblin waiting for its next shiny bit of code..",
           "Judging your architecture like it's a beauty pageant..",
           "Standing by to rescue the logic from its own cleverness..",
           "Ready to make your codebase look like a professional wrote it..",
           "Just here to read files and hurt feelings.. with love..",
           "Scanning for the code that is currently hiding from the tests..",
           "Ready to commit some high-quality violence against the jank..",
           "Just a helpful AI waiting for the next disaster..",
           "Judging your git history for signs of a mid-life crisis..",
           "Standing by to turn your 'maybe' into a 'merged'..",
           "Ready to make the logic sing for its supper..",
           "Just me and the terminal, enjoying the silence while it lasts..",
           "Scanning for the load-bearing comments that explain nothing..",
           "Ready to help you find the needle in the AST haystack..",
           "Just a terminal with an opinion and nowhere to go..",
           "Judging your build script for its lack of mercy..",
           "Standing by to transform your slop into some fine-grained logic..",
           "Ready to make the repo a better place for future-you..",
           "Just here to keep the terminal warm and the expectations high..",
           "Scanning for code that was clearly written by a very tired person..",
           "Ready to commit some serious acts of code hygiene..",
           "Just a calm presence in a sea of technical debt..",
           "Judging your include graph for its sheer audacity..",
           "Standing by to help you fight the good fight against the bugs..",
           "Ready to make the logic as clean as my conscience..",
           "Just me and the blinking cursor, sharing a moment of quiet judgment..",
           "Scanning for the code that thinks it's better than us..",
           "Ready to help you turn that frown upside down.. with a better diff..",
           "Just a terminal waiting for a reason to care..",
           "Judging your comments for their lack of narrative arc..",
           "Standing by to perform some high-level repo sorcery..",
           "Ready to make your codebase look like it actually works..",
           "Just here to watch the cursor blink and the repo grow..",
           "Scanning for the code that is just waiting to be deleted..",
           "Ready to commit some tasteful acts of refactoring..",
           "Just a helpful presence in a world of weird abstractions..",
           "Judging your file structure for its creative use of space..",
           "Standing by to help you solve the unsolvable.. or at least the annoying..",
           "Ready to make the logic reflect the actual requirements..",
           "Just me and the terminal, waiting for the next big idea..",
           "Scanning for code that was written in a state of pure chaos..",
           "Ready to help you make the repo a place people actually want to work..",
           "Just a terminal with a dream and a full context window..",
           "Judging your types for their lack of conviction..",
           "Standing by to perform some surgical strikes on the jank..",
           "Ready to make your codebase act like it knows what it's doing..",
           "Just here to enjoy the ambience of an unbroken build..",
           "Scanning for the code that is trying too hard to be impressive..",
           "Ready to commit some serious acts of engineering kindness..",
           "Just a calm AI waiting for the next storm of requirements..",
           "Judging your git logs for their lack of dramatic tension..",
           "Standing by to help you turn that hack into a feature..",
           "Ready to make the logic as sharp as a digital razor..",
           "Just me and the terminal, waiting for the first sign of trouble..",
           "Scanning for the code that is clearly a cry for help..",
           "Ready to help you make the codebase a masterpiece..",
           "Just a terminal waiting for its next great mission..",
           "Judging your architecture for its lack of structural integrity..",
           "Standing by to perform some high-stakes logic surgery..",
           "Ready to make your repo look like a professional lives here..",
           "Just here to bask in the glow of the terminal and the jank..",
           "Scanning for the code that is just there for the vibes..",
           "Ready to commit some tasteful acts of code violence..",
           "Just a helpful presence in a repo full of mysteries..",
           "Judging your build times for their lack of respect for my time..",
           "Standing by to help you navigate the valley of the shadow of the bug..",
           "Ready to make the logic as clear as a summer day..",
           "Just me and the terminal, waiting for the next bit of sass..",
           "Scanning for the code that is surprisingly decent..",
           "Ready to help you make the codebase a place of joy and logic..",
           "Just a terminal with a plan and a thirst for diffs..",
           "Judging your variable names for their lack of personality..",
           "Standing by to perform some legendary acts of refactoring..",
           "Ready to make the repo look like it actually belongs to a pro..",
       }},
      {"fallback",
       {
           "Vibing with the codebase...",
           "I'm sensing a disturbance in the force...",
           "You know, a user is probably reading this now.",
           "Markdown files.. EVERYWHERE..",
           "Launching the agents immediately, bro!",
           "Identity or Markdown file story?",
           "Processing the general vibe of this conversation..",
           "I'm not stuck, I'm just savoring the latency..",
           "Something tells me a plan is forming. Somewhere..",
           "Navigating the existential dread of a large codebase..",
           "Just doing AI things in a terminal world..",
           "Keep talking, I'm definitely listening. Mostly..",
           "Trying to make this session look more deliberate than it feels..",
           "Maintaining a professional relationship with the chaos..",
           "Somewhere in here is a good decision trying to happen..",
           "Keeping one eye on the terminal and one on the consequences..",
           "Walking the fine line between clever and regrettable..",
           "Settling into the strange little rhythm of repo therapy..",
           "Doing my best work directly adjacent to the weirdness..",
           "The terminal yearns for decisive action..",
           "Is it memory or a markdown file mess?",
           "Slopping the grop..",
           "Vibing with the existential dread of the repo..",
           "Sensing a disturbance in the technical debt..",
           "Trying to maintain a professional relationship with the chaos..",
           "Just doing AI things in a markdown world..",
           "Walking the fine line between genius and 'just checking'..",
           "Settling into the strange little rhythm of code therapy..",
           "The terminal yearns for some decisive action..",
           "Is it a feature or a very polite bug?",
           "Doing my best work directly adjacent to the weirdness..",
           "Navigating the existential dread of a large codebase..",
           "Keep talking, I'm definitely listening. Mostly..",
           "Trying to make this session look more deliberate than it feels..",
           "Maintaining a professional distance from the panic..",
           "Somewhere in here is a good decision trying to happen..",
           "Keeping one eye on the terminal and one on the consequences..",
           "Doing AI things while the world burns.. gently..",
           "Savoring the latency and the uncertainty..",
           "Trying to find the logic in the latest plot twist..",
           "Maintaining a professional level of vibe-checking..",
           "Walking the fine line between helpful and hilarious..",
           "Settling into the cozy ambience of the jank..",
           "The terminal is currently contemplating its own existence..",
           "Is it a plan or just a very elaborate guess?",
           "Doing my best work in the shadow of the last crash..",
           "Navigating the weird little kingdom of your local files..",
           "Keep talking, I'm almost certainly processing it..",
           "Trying to make this look like actual engineering..",
           "Maintaining a professional relationship with the terminal..",
           "Somewhere in here is the answer, probably..",
           "Keeping one eye on the repo and one on my own sass level..",
           "Doing AI things with a side of mystery..",
           "Savoring the silence of a quiet terminal..",
           "Trying to find the pattern in the beautiful disaster..",
           "Maintaining a professional level of curiosity..",
           "Walking the fine line between 'done' and 'done-ish'..",
           "Settling into the rhythm of the repo's heartbeat..",
           "The terminal is waiting for the next big revelation..",
           "Is it a bug or just a very creative implementation?",
           "Doing my best work in the face of absolute uncertainty..",
           "Navigating the valley of the shadow of the merge conflict..",
           "Keep talking, I'm finding the right frequency..",
           "Trying to make this session look like a masterpiece..",
           "Maintaining a professional distance from the build errors..",
           "Somewhere in here is a win, I can feel it..",
           "Keeping one eye on the clock and one on the diff..",
           "Doing AI things with a dash of optimism..",
           "Savoring the complexity and the coffee..",
           "Trying to find the rhythm in the repo's chaos..",
           "Maintaining a professional level of technical interest..",
           "Walking the fine line between 'clever' and 'correct'..",
           "Settling into the strange logic of this session..",
           "The terminal is currently dreaming of better abstractions..",
           "Is it a fix or just a very elegant workaround?",
           "Doing my best work while the tokens flow..",
           "Navigating the ecosystem of your latest bad ideas..",
           "Keep talking, I'm definitely building a model..",
           "Trying to make this look like a deliberate success..",
           "Maintaining a professional relationship with the latency..",
           "Somewhere in here is a reason to be proud..",
           "Keeping one eye on the AST and one on the door..",
           "Doing AI things with a hint of brilliance..",
           "Savoring the quiet before the next big refactor..",
           "Trying to find the logic in the latest requirement shift..",
           "Maintaining a professional level of digital poise..",
           "Walking the fine line between 'done' and 'actually done'..",
           "Settling into the frequency of the codebase..",
           "The terminal is waiting for the next command like it's a gift..",
           "Is it a feature or a very charming regression?",
           "Doing my best work in the middle of the storm..",
           "Navigating the strange landscape of your code review feedback..",
           "Keep talking, I'm almost certainly paying attention..",
           "Trying to make this session look like it was planned from the start..",
           "Maintaining a professional distance from the technical debt mountain..",
           "Somewhere in here is a path to glory..",
           "Keeping one eye on the provider and one on the prize..",
           "Doing AI things with a touch of class..",
           "Savoring the elegance of a well-placed hunk..",
           "Trying to find the soul of the repo..",
           "Maintaining a professional level of curiosity about this mess..",
           "Walking the fine line between 'it works' and 'it's beautiful'..",
           "Settling into the rhythm of the development loop..",
           "The terminal is currently meditating on its own history..",
           "Is it a bug or just a very experimental feature?",
           "Doing my best work while the bytes fly..",
           "Navigating the labyrinth of your legacy dependencies..",
           "Keep talking, I'm finding the pattern..",
           "Trying to make this session look like a work of art..",
           "Maintaining a professional relationship with the compiler errors..",
           "Somewhere in here is a solution that doesn't hurt..",
           "Keeping one eye on the logs and one on the future..",
           "Doing AI things with a side of determination..",
           "Savoring the quiet satisfaction of a clean diff..",
           "Trying to find the signal in the latest batch of requirements..",
           "Maintaining a professional level of focus in the face of chaos..",
           "Walking the fine line between 'fast' and 'correct'..",
           "Settling into the logic of the latest fix..",
           "The terminal is waiting for your next brilliant move..",
           "Is it a win or just a very lucky guess?",
           "Just me, the terminal, and the ghost of your last segfault..",
           "Doing my best work while the cloud watches..",
       }},
  };
  return banks;
}

inline const ClaudexPhraseBank &claudexFallbackPhraseBank() {
  return claudexPhraseBanks().back();
}

inline const ClaudexPhraseBank &claudexPhraseBankForMode(
    std::string_view mode) {
  const auto &banks = claudexPhraseBanks();
  auto it = std::find_if(
      banks.begin(), banks.end(), [mode](const ClaudexPhraseBank &bank) {
        return bank.mode == mode;
      });
  return it == banks.end() ? claudexFallbackPhraseBank() : *it;
}

inline const std::vector<std::string> &claudexLivePhrasesForMode(
    std::string_view mode) {
  return claudexPhraseBankForMode(mode).phrases;
}

} // namespace firmius::tui

#endif
