#!/usr/bin/env bun

import { readFile, writeFile, readdir } from "node:fs/promises";
import { join } from "node:path";

const ROOT = process.cwd();
const PURPOSES_DIR = join(ROOT, "prompts");
const OUTPUT_FILE = join(ROOT, "packages/cli/src/purposes.embedded.ts");

const FRONTMATTER_DELIMITER = "---";
const PURPOSE_FILE_EXTENSION = ".md";

interface PurposeFrontmatter {
  name: string;
  title: string;
  description: string;
  scopes: string[];
  canSpawn?: string[];
}

interface PurposeDefinition {
  name: string;
  title: string;
  description: string;
  scopes: string[];
  canSpawn: string[];
  systemPrompt: string;
}

async function parsePurposeFile(content: string): Promise<PurposeDefinition> {
  const trimmed = content.trimStart();
  if (!trimmed.startsWith(FRONTMATTER_DELIMITER)) {
    throw new Error("Missing YAML frontmatter — file must start with ---");
  }

  const afterFirstDelimiter = trimmed.slice(FRONTMATTER_DELIMITER.length);
  const closingIndex = afterFirstDelimiter.indexOf(
    `\n${FRONTMATTER_DELIMITER}`,
  );
  if (closingIndex === -1) {
    throw new Error("Missing closing --- for YAML frontmatter");
  }

  const yamlBlock = afterFirstDelimiter.slice(0, closingIndex);
  const body = afterFirstDelimiter
    .slice(closingIndex + 1 + FRONTMATTER_DELIMITER.length)
    .trim();

  const yaml = await import("yaml");
  const frontmatter = yaml.parse(yamlBlock) as PurposeFrontmatter;

  return {
    name: frontmatter.name,
    title: frontmatter.title,
    description: frontmatter.description,
    scopes: frontmatter.scopes,
    canSpawn: Array.isArray(frontmatter.canSpawn)
      ? frontmatter.canSpawn
      : [],
    systemPrompt: body,
  };
}

async function embedPurposes(): Promise<void> {
  console.log("📂 Reading purpose files from:", PURPOSES_DIR);

  const entries = await readdir(PURPOSES_DIR);
  const mdFiles = entries.filter((f) => f.endsWith(PURPOSE_FILE_EXTENSION));

  console.log(`📄 Found ${mdFiles.length} purpose files`);

  const purposes: PurposeDefinition[] = [];

  for (const file of mdFiles) {
    const filePath = join(PURPOSES_DIR, file);
    const content = await readFile(filePath, "utf-8");
    const definition = await parsePurposeFile(content);
    purposes.push(definition);
    console.log(`  ✓ Parsed: ${definition.name}`);
  }

  const output = `// Auto-generated by scripts/embedPurposes.ts
// Do not edit manually

import type { PurposeDefinition } from "@firmius/core";

export const EMBEDDED_PURPOSES: PurposeDefinition[] = ${JSON.stringify(purposes, null, 2)};
`;

  await writeFile(OUTPUT_FILE, output, "utf-8");
  console.log(`✅ Wrote embedded purposes to: ${OUTPUT_FILE}`);
}

embedPurposes().catch((err) => {
  console.error("❌ Failed to embed purposes:", err);
  process.exit(1);
});
