[package]
name = "firmius-audits"
version = "0.0.3"
edition = "2024"

[[bin]]
name = "firmius-audits"
path = "src/main.rs"

[dependencies]
firmius-core = { path = "../core" }
futures.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true